<?php

/**
 * JobeetJob
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class JobeetJob extends BaseJobeetJob
{
  public function __tostring()
  {
    return sprintf('%s at %s (%s)', $this->getPosition(), $this->getCompany(), $this->getLocation());
  }

  public function getCompanySlug()
  {
    return Jobeet::slugfy($this->getCompany());
  }

  public function getPositionSlug()
  {
    return Jobeet::slugfy($this->getPosition());
  }

  public function getLocationSlug()
  {
    return Jobeet::slugfy($this->getLocation());
  }
}
